addr:
  {{- $chartReleaseName := (index .Vars.extraDeploy 3).metadata.name }}
  tcp://{{ $chartReleaseName }}:80:
    reachable: true
    timeout: 2000
  tcp://podinfo:9898:
    reachable: true
    timeout: 2000
